#!/usr/bin/env python3
"""Extract mechanical datums from the active Rev F board (no KiCad dependency)."""
from pathlib import Path
import hashlib
import json
from cad_sexpr import parse, children, child, prop
ROOT = Path(__file__).resolve().parents[1]
board = ROOT / 'hardware/rev-f/mesh-phone.kicad_pcb'
r = parse(board.read_text())
points = [list(map(float, child(line, key)[1:3]))
          for line in children(r, 'gr_line') if child(line, 'layer')[1] == 'Edge.Cuts'
          for key in ('start', 'end')]
x0, y0 = map(min, zip(*points))
x1, y1 = map(max, zip(*points))
fps = {str(prop(f, 'Reference')[2]): f for f in children(r, 'footprint')}
def pos(ref):
    x, y = map(float, child(fps[ref], 'at')[1:3])
    return [round(x-(x0+x1)/2, 4), round((y0+y1)/2-y, 4)]
values = {'pcb_w': x1-x0, 'pcb_h': y1-y0,
          'mounts': [pos(f'H{i}') for i in range(1, 5)],
          'keys': [pos(f'SW{i}') for i in range(2, 18)],
          'usb': pos('USB1'), 'power': pos('SW1'), 'expansion': pos('J16')}
out = ROOT / 'mechanical/enclosure/pcb_geometry.scad'
out.write_text('// Generated by scripts/enclosure_geometry.py; KiCad Y is inverted.\n'
               '// PCB SHA256: '+hashlib.sha256(board.read_bytes()).hexdigest()+'\n'
               + ''.join(f'{k} = {json.dumps(v)};\n' for k,v in values.items()))
print(out.relative_to(ROOT))
